SELECT * WHERE {
  ?item wdt:P31 wd:Q755707 ;
  OPTIONAL { ?item wdt:P1476 ?title. }
  OPTIONAL { ?item wdt:P2044 ?elevation. }
  OPTIONAL { ?item wdt:P856 ?url. }
  OPTIONAL { ?item wdt:P94 ?coa. }
  OPTIONAL { ?item wdt:P571 ?inception. }
  OPTIONAL { ?item wdt:P576 ?dissolved. }
  OPTIONAL { ?item wdt:P402 ?osm. }
  OPTIONAL {
    ?article schema:about ?item;
      schema:isPartOf <https://no.wikipedia.org/>.
  }
#  FILTER(NOT EXISTS{?item wdt:P31 wd:Q515})
 SERVICE wikibase:label {
    bd:serviceParam wikibase:language "nb".
    ?item rdfs:label ?itemLabel.
  }}
