PREFIX pqv: <http://www.wikidata.org/prop/qualifier/value/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT *
WHERE
{
  ?kommune wdt:P31 wd:Q755707.
  ?kommune wdt:P2504 ?knr.
  ?kommune p:P2504 ?code.
  OPTIONAL { ?code  pq:P580 ?start_time. }
  OPTIONAL { ?code  pq:P582 ?end_time . }
}
