name: build and publish kommune

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm update
      - run: npm run download
      - run: npm run transform
      - name: Check downloaded files
        run: ./.github/workflows/filecheck.sh
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: artsdatabanken/kommune
          path: './destinationRepo'
          token: ${{secrets.PUSH_TOKEN}}
      - name: Run deployment script
        run: ./.github/workflows/deploy.sh 
        shell: bash
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts.tar"
          tag: v_${{ github.run_number }}
      - name: post to slack
        run: ./.github/workflows/slack.sh ${{ secrets.POST_SLACK }}
        shell: bash
      - name: Push to kommune
        run: |
          cd destinationRepo
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --global --list
          git stage .
          git commit -m "Updated from kommune v_${{ github.run_number }}"
          git branch --set-upstream-to master
          git push https://$USERNAME:$REPO_KEY@github.com/artsdatabanken/kommune.git
        env:
          REPO_KEY: ${{secrets.PUSH_TOKEN}}
          USERNAME: github-actions[bot]